DROP TABLE IF EXISTS users;

CREATE TABLE users (
    username TEXT PRIMARY KEY NOT NULL UNIQUE,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bio TEXT NOT NULL
    userId INT AUTO_INCREMENT NOT NULL UNIQUE
);